// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/common/layout/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoadingIcon: typeof import('./src/components/common/icon/LoadingIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WikiTip: typeof import('./src/components/common/message/WikiTip.vue')['default']
  }
}
